openapi: 3.0.0
info:
  title: GitLab REST API V4
  description: > 
    This is an OpenAPI specification for the GitLab REST API. <br><br>
    See <a href="https://docs.gitlab.com/ee/api/api_resources.html">REST API resources</a> 
    on gitlab.org for a detailed description of the REST API.
  version: 0.0.1
servers:
  - url: https://gitlab.com/api
    description: Base REST URI of API version 4 to 'gitlab.com'.

paths:

  # PROJECT
  # /v4/projects:
  #   $ref: "./v4/paths/projects/projects.yaml"
  # /v4/projects/{id}:
  #   $ref: "./v4/paths/projects/projects_id.yaml"
  /v4/projects/{id}/issues:
    $ref: "./v4/paths/projects/issues.yaml"
  /v4/projects/{id}/issues/{iid}:
    $ref: "./v4/paths/projects/issues_iid.yaml"
  /v4/projects/{id}/issues/{iid}/reorder:
    $ref: "./v4/paths/projects/issues_iid_reorder.yaml"
  /v4/projects/{id}/issues/{iid}/move:
    $ref: "./v4/paths/projects/issues_iid_move.yaml"
  /v4/projects/{id}/issues/{iid}/subscribe:
    $ref: "./v4/paths/projects/issues_iid_subscribe.yaml"
  /v4/projects/{id}/issues/{iid}/unsubscribe:
    $ref: "./v4/paths/projects/issues_iid_unsubscribe.yaml"
  /v4/projects/{id}/issues/{iid}/todo:
    $ref: "./v4/paths/projects/issues_iid_todo.yaml"
  /v4/projects/{id}/issues/{iid}/time_stats:
    $ref: "./v4/paths/projects/issues_iid_time_stats.yaml"


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []