type: object
properties:
  id: 
    type : string
  description: 
    type : string
  name: 
    type : string
  name_with_namespace: 
    type : string
  path: 
    type : string
  path_with_namespace: 
    type : string
  created_at:
    type : string
    format: date-time
  default_branch: 
    type : string
  tag_list: [] #TODO: 20210822 CJ: What type is used here?
  topics: [] #TODO: 20210822 CJ: What type is used here?
  ssh_url_to_repo:
    type: string
    format: uri
  http_url_to_repo:
    type: string
    format: uri
  web_url:
    type: string
    format: uri
  readme_url:
    type: string
    format: uri
  avatar_url:
    type: string
    format: uri
  forks_count:
    type: integer
  star_count:
    type: integer
  last_activity_at:
    type: string
    format: date-time
  namespace: 
    $ref: "./namespace.yaml"
  container_registry_image_prefix:
    type: string
  _links: 
    $ref: "./links.yaml"
  packages_enabled:
    type: boolean
  empty_repo:
    type: boolean
  archived":
    type: boolean
  visibility:
    $ref: "../../enums/visibility.yaml"
  owner: 
    $ref: "./user.yaml"
  resolve_outdated_diff_discussions:
    type: boolean
  container_expiration_policy: 
    $ref: "./expirationPolicy.yaml"
  issues_enabled:
    type: boolean
  merge_requests_enabled:
    type: boolean
  wiki_enabled:
    type: boolean
  jobs_enabled:
    type: boolean
  snippets_enabled:
    type: boolean
  container_registry_enabled:
    type: boolean
  service_desk_enabled:
    type: boolean
  service_desk_address:
    type: string
    format: email
  can_create_merge_request_in:
    type: boolean
  issues_access_level:
    type: string
    # TODO: 20210822 CJ: Clarify which values are possible here!
  repository_access_level:
    type: string
    # TODO: 20210822 CJ: Clarify which values are possible here!
  merge_requests_access_level:
    type: string
    # TODO: 20210822 CJ: Clarify which values are possible here!
  forking_access_level:
    type: string
    # TODO: 20210822 CJ: Clarify which values are possible here!
  wiki_access_level:
    type: string
    # TODO: 20210822 CJ: Clarify which values are possible here!
  builds_access_level:
    type: string
  snippets_access_level:
    type: string
    # TODO: 20210822 CJ: Clarify which values are possible here!
  pages_access_level:
    type: string
    # TODO: 20210822 CJ: Clarify which values are possible here!
  operations_access_level:
    type: string
    # TODO: 20210822 CJ: Clarify which values are possible here!
  analytics_access_level:
    type: string
    # TODO: 20210822 CJ: Clarify which values are possible here!
  container_registry_access_level:
    type: string
    # TODO: 20210822 CJ: Clarify which values are possible here!
  emails_disabled:
    type: boolean
    nullable: true
  shared_runners_enabled:
    type: boolean
  lfs_enabled:
    type: boolean
  creator_id:
    type: integer
  import_status:
    $ref: "../../enums/importerStatus.yaml"
  import_error:
    type: string
    nullable: true
  open_issues_count:
    type: integer
  runners_token:
    type: string
  ci_default_git_depth:
    type: integer
  ci_forward_deployment_enabled:
    type: boolean
  ci_job_token_scope_enabled:
    type: boolean
  public_jobs:
    type: boolean
  build_git_strategy:
    $ref: "../../enums/buildGitStrategy.yaml"
  build_timeout:
    type: integer
  auto_cancel_pending_pipelines:
    $ref: "../../enums/enablement.yaml"
  build_coverage_regex:
    type: string
    nullable: true
  ci_config_path:
    type: string
  shared_with_groups:
    type: array
    items: 
      $ref: "./sharedGroupWithProject.yaml"
  only_allow_merge_if_pipeline_succeeds: false,
  allow_merge_on_skipped_pipeline: null,
  restrict_user_defined_variables: false,
  request_access_enabled: true,
  only_allow_merge_if_all_discussions_are_resolved: false,
  remove_source_branch_after_merge: true,
  printing_merge_request_link_enabled: true,
  merge_method: "merge",
  squash_option: "default_off",
  suggestion_commit_message: null,
  auto_devops_enabled: false,
  auto_devops_deploy_strategy: "continuous",
  autoclose_referenced_issues: true,
  keep_latest_artifact: true,
  external_authorization_classification_label: "",
  requirements_enabled: false,
  security_and_compliance_enabled: true,
  compliance_frameworks: [],
  permissions: {
      "project_access": {
          "access_level": 40,
          "notification_level": 3
      },
      "group_access": null
  }