name: "Publish"

on: [push]
# on:
#   push:
#     tags:
#       - "v**.**.**" # Semantic Versioning like "v1.22.3"
#       - "v**.**.**-**" # Prerelease Semantic Versioning like "v1.22.3-rc4"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Test Packing
        run: ./build/build.sh -Target Pack -Configuration Release --nuget_api_key_gitlabclient ${{ secrets.NUGET_API_KEY_GITLABCLIENT }}

      # - name: Run publish with nuke
      #   run: ./build/build.sh -Target Publish -Configuration Release --nuget_api_key_gitlabclient ${{ secrets.NUGET_API_KEY_GITLABCLIENT }}
